name: Deploy Static HTML to EC2 via SSM (OIDC Only)

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::YOUR_ACCOUNT_ID:role/YOUR_OIDC_DEPLOY_ROLE
          aws-region: us-east-1

      - name: Zip static site
        run: cd dev && zip -r ../site.zip . && cd ..

      - name: Upload artifact to S3 (for EC2 to pull)
        run: aws s3 cp site.zip s3://YOUR_BUCKET_NAME/site.zip

      - name: Deploy to EC2 via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=i-0abc12345def67890" \
            --comment "Deploy static site via OIDC" \
            --parameters 'commands=[
              "aws s3 cp s3://YOUR_BUCKET_NAME/site.zip /tmp/site.zip",
              "unzip -o /tmp/site.zip -d /var/www/html/",
              "systemctl reload apache2"
            ]' \
            --region us-east-1
