name: Pull Code to EC2 via SSM (OIDC Only)

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::779846824575:role/dev-test
          aws-region: us-west-2

      - name: Pull code on EC2 via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=i-0e5068542b0d073d6" \
            --comment "Git pull from GitHub repo into /home/ubuntu" \
            --parameters 'commands=[
              "cd /home/ubuntu",
              "if [ ! -d stage-1 ]; then git clone https://github.com/mohit10004/stage-1.git; else cd stage-1 && git pull; fi"
            ]' \
            --region us-west-2 \
            --output text
